spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/api/v1/auth/oauth2/callback/kakao"
            scope: profile_nickname, account_email
          google:
            redirect-uri: "{baseUrl}/api/v1/auth/oauth2/callback/google"
            scope: profile, email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  servlet:
    context-path: /api/v1

jwt:
  access-expiration: 3600000
  refresh-expiration: 604800000